### ISSUE TITLE
Mail (Hospital->Student) funktioniert nicht mehr

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#371]
http://localhost:8000/iamstudent/send_mail_student/1
Senden ...

Fehlerursache:
Für die Mail ans Hospital wird bei ============= der Text gesplittet, das scheint aber gar nicht vorhanden zu sein..

Trace

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/iamstudent/send_mail_student/1

Django Version: 3.0.4
Python Version: 3.8.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_filters',
 'widget_tweaks',
 'crispy_forms',
 'django_tables2',
 'apps.mapview',
 'apps.iamstudent',
 'apps.ineedstudent',
 'apps.accounts',
 'apps.use_statistics']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware']



Traceback (most recent call last):
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\malte\Documents\Projects\match4healthcare\backend\apps\iamstudent\views.py", line 115, in send_mail_student_id_list
    send_mails_for(request.user.hospital)
  File "C:\Users\malte\Documents\Projects\match4healthcare\backend\apps\iamstudent\views.py", line 137, in send_mails_for
    text = emails[0].message.split('===============================================')[1]

Exception Type: IndexError at /iamstudent/send_mail_student/1
Exception Value: list index out of range
```

**Comment by maltezacharias** [comment]
Closed in v1.5
