### ISSUE TITLE
Entering too high search radius leads to exception

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#372]
http://localhost:8000/ineedstudent/students/DE/21033/10?countrycode=DE&plz=21033&distance=9999&availability_start=&braucht_bezahlung=&unterkunft_gewuenscht=

**Initial analysis:** Too many zip codes in select statement lead to error

**Proposed Solution:** Check Distance and only allow up to xx km distance, check number of affected zip codes before performing query to prevent this error. 

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/ineedstudent/students/DE/21033/10?countrycode=DE&plz=21033&distance=9999&availability_start=&braucht_bezahlung=&unterkunft_gewuenscht=

Django Version: 3.0.4
Python Version: 3.8.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_filters',
 'widget_tweaks',
 'crispy_forms',
 'django_tables2',
 'apps.mapview',
 'apps.iamstudent',
 'apps.ineedstudent',
 'apps.accounts',
 'apps.use_statistics']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware']



Traceback (most recent call last):
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (too many SQL variables) was the direct cause of the following exception:
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\malte\Documents\Projects\match4healthcare\backend\apps\iamstudent\views.py", line 228, in student_list_view
    enable_mail_send = (filter_jobrequirements.qs.count() <= max_mails)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 397, in count
    return self.query.get_count(using=self.db)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\query.py", line 517, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\query.py", line 502, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\malte\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /ineedstudent/students/DE/21033/10
Exception Value: too many SQL variables
```

**Comment by feeds** [comment]
catch exception

**Comment by feeds** [comment]
it is an limitation of SQlite, not an issue of the production environment
