### ISSUE TITLE
Clear error message for permission error of statistics

### ISSUE THREAD

**Issue by bjrne** [Baschdl/match4healthcare#485]
When `backend/run/gunicorn-access.log` cannot be accessed, redirect staff user to simple HTTPRedirect Error message "gunicorn-access.log cannot be accessed due to a permission error" instead of an internal server error 500.

```bash
21:06:27,836: django.request ERROR    |Internal Server Error: /use_statistics/view|'Traceback (most recent call last):
  File "/home/bjarne/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bjarne/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bjarne/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bjarne/.local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view\n    return view_func(request, *args, **kwargs)
  File "/home/bjarne/.local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view\n    return view_func(request, *args, **kwargs)
  File "/home/bjarne/m4h_local/match4healthcare/backend/apps/use_statistics/views.py", line 25, in use_statistics\n    data = process_file(ttl_hash=get_ttl_hash(60))
  File "/home/bjarne/m4h_local/match4healthcare/backend/apps/use_statistics/views.py", line 33, in process_file
    requests = parse_file()\n  File "/home/bjarne/m4h_local/match4healthcare/backend/apps/use_statistics/views.py", line 63, in parse_file
    with open(os.path.join(settings.RUN_DIR, logfile_name), "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: \'/home/bjarne/m4h_local/match4healthcare/backend/run/gunicorn-access.log\''|
```

**Comment by Baschdl** [comment]
Is it really a permission error or does it not exist in your local installation yet?
